[package]
name = "freq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.18"
infer = "0.7.0"
pdf-extract = "0.6.4"
